# -*- coding: utf-8 -*-
#https://www.colordic.org/
[theme]
primaryColor="#ffd700" # ポイント
backgroundColor="#483d8b" # 背景
secondaryBackgroundColor="#ba55d3" # 左背景
textColor="#FFFFFF" # 白
font="sans serif"